@startuml

' Define external actors
actor actor_admin as "Administrator"
actor actor_display as "Display"

' Define Services
cloud service_elasticsearch as "Service: elasticsearch"
cloud service_search_node as "Service: search_node"
cloud service_middleware as "Service: middleware"
cloud service_admin_db as "Service: admin-db"
cloud service_admin as "Service: admin"
cloud service_screen as "Service: screen"
cloud service_redis as "Service: redis"

' Define ingresses
rectangle ingress_admin as "Ingress: Admin"
rectangle ingress_screen as "Ingress: Screen"
rectangle ingress_search as "Ingress: Search"

' Define volumes
storage storage_uploads as "volume: uploads"
storage storage_datadir as "volume: datadir"
storage storage_esdata as "volume: esdata"

' Define deployments and their containers
together {
  frame deployment_admin as "deployment: admin" {
    together {
      artifact admin_nginx as "admin-nginx"
      artifact admin_php as "admin-php"
    }
    artifact admin_release as "admin-release"

    ' Internal storage so no volume
    storage storage_release_src as "emptyDir: release source"
  }

  frame deployment_admin_db as "deployment: admin-db" {
    artifact mariadb as "mariadb:10.3"
  }
}

together {
  frame deployment_elasticsearch as "deployment: elasticsearch" {
    artifact elasticsearch
  }

  frame deployment_search as "deployment: search" {
    artifact search_node
  }
}

together {
  frame deployment_redis as "deployment: redis" {
    artifact redis
  }

  frame deployment_middleware as "deployment: middleware" {
    artifact middleware
  }
}

frame deployment_screen as "deployment: screen" {
  artifact screen
}

' Connect containers to storage
admin_release -d- storage_release_src
admin_nginx -d- storage_release_src
admin_php -d- storage_release_src
admin_php --- storage_uploads
mariadb --- storage_datadir
elasticsearch --- storage_esdata

' Connect services to containers
service_admin -d--> admin_nginx
service_middleware -d--> middleware
service_screen -d--> screen
service_elasticsearch -d--> elasticsearch
service_admin_db -d--> mariadb
service_redis -d--> redis
service_search_node -d--> search_node

' Inter-container communication
admin_php -u--> service_admin_db
admin_php -u--> service_middleware
admin_php -u--> service_elasticsearch
search_node -u--> service_elasticsearch
middleware -u--> service_redis
screen -u--> service_middleware
screen -u--> service_admin
admin_nginx -> admin_php

' Connect ingresses to services
ingress_admin -d-> service_admin
ingress_screen -d-> service_screen
ingress_search -d-> service_search_node

' Connect external users to ingress
actor_admin -d-> ingress_admin
actor_admin -d-> ingress_search
actor_display -d-> ingress_screen

@enduml
