parameters:
    database_driver: pdo_mysql
    database_host: admin-db
    database_port: null
    database_name: os2display
    database_user: os2display
    database_password: os2display
    database_server_version: 5.5
    mailer_transport: smtp
    mailer_host: mailhog
    mailer_user: null
    mailer_port: 1025
    mailer_password: null
    mailer_from_email: admin@example.com
    mailer_from_name: Admin
    locale: da
    secret: ThisTokenIsNotSoSecretChangeIt
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true
    absolute_path_to_server: 'https://admin.bbs-os2display.docker'
    zencoder_api: 1234567890
    sharing_host: 'http://search:3010'
    sharing_path: /api
    sharing_apikey: 88cfd4b277f3f8b6c7c15d7a84784067
    sharing_enabled: true
    search_host: 'http://search:3010'
    search_host_public: 'https://search.bbs-os2display.docker'
    search_path: /api
    search_apikey: 795359dd2c81fa41af67faa2f9adbd32
    search_index: e7df7cd2ca07f4f1ab415d457a6e1c13
    middleware_host: 'http://middleware:3020'
    middleware_path: /api
    middleware_apikey: 059d9d9c50e0c45b529407b183b6a02f
    site_title: 'OS2 display BBS - docker'
    version: dev
    itk_log_version: 1
    itk_log_error_callback: /api/error
    itk_log_log_to_console: true
    itk_log_log_level: all
    search_filter_default: all
